#!/bin/bash

if [ -n "${QPSMTPD_ENABLE_RCPT_MYSQL}" ]; then

    if [ -z "${QPSMTPD_RCPT_MYSQL_DATABASE}" ]; then
        echo "missing QPSMTPD_RCPT_MYSQL_DATABASE"
        exit 255
    fi

    if [ -z "${QPSMTPD_RCPT_MYSQL_PORT}" ]; then
        QPSMTPD_RCPT_MYSQL_PORT=3306
    fi

    if [ -z "${QPSMTPD_RCPT_MYSQL_CACHETIMEOUT}" ]; then
        QPSMTPD_RCPT_MYSQL_CACHETIMEOUT=500
    fi

    if [ -z "${QPSMTPD_RCPT_MYSQL_HOST}" ]; then
        echo "missing QPSMTPD_RCPT_MYSQL_HOST"
        exit 255
    fi

    if [ -z "${QPSMTPD_RCPT_MYSQL_USER}" ]; then
        echo "missing QPSMTPD_RCPT_MYSQL_USER"
        exit 255
    fi

    if [ -z "${QPSMTPD_RCPT_MYSQL_PASS}" ]; then
        echo "missing QPSMTPD_RCPT_MYSQL_DATABASE"
        exit 255
    fi

    if [ -z "${QPSMTPD_RCPT_MYSQL_QUERY}" ]; then
        echo "missing QPSMTPD_RCPT_MYSQL_QUERY"
        exit 255
    fi

    #
    # create configuration file
    #
    rm -rf /etc/qpsmtpd/rcpt_mysql
    echo "database:=${QPSMTPD_RCPT_MYSQL_DATABASE}" >> /etc/qpsmtpd/rcpt_mysql
    echo "host:=${QPSMTPD_RCPT_MYSQL_HOST}" >> /etc/qpsmtpd/rcpt_mysql
    echo "port:=${QPSMTPD_RCPT_MYSQL_PORT}" >> /etc/qpsmtpd/rcpt_mysql
    echo "user:=${QPSMTPD_RCPT_MYSQL_USER}" >> /etc/qpsmtpd/rcpt_mysql
    echo "pass:=${QPSMTPD_RCPT_MYSQL_PASS}" >> /etc/qpsmtpd/rcpt_mysql
    echo "host:=${QPSMTPD_RCPT_MYSQL_HOST}" >> /etc/qpsmtpd/rcpt_mysql
    echo "cachetimeout:=${QPSMTPD_RCPT_MYSQL_CACHETIMEOUT}" >> /etc/qpsmtpd/rcpt_mysql
    echo "query:=${QPSMTPD_RCPT_MYSQL_QUERY}" >> /etc/qpsmtpd/rcpt_mysql


    # enable plugin
    echo "rcpt_mysql" >> /etc/qpsmtpd/plugins

fi
